# AUTO-GENERATED by parser/translate_oracle.py -- do not hand-edit.
HAND_ABILITIES = [
    ('Balamb T-Rexaur', '2', "self.controller.search_lib(lambda _c: _c.is_land and _c.has_subtype('Forest'))", None),
    ('Rubblebelt Maaka', 'R', "[t.add_effect('modifyPT', (3, 3), self, self.game.eot_time) for t in self.legal_targets]", ["'target attacking creature'"]),
    ('Stir the Sands', '3B', 'self.controller.draw(1)', None),
    ('Viashino Shanktail', '2R', "[t.add_effect('modifyPT', (3, 1), self, self.game.eot_time) for t in self.legal_targets]", ["'target attacking creature'"]),
]
